package com.example.rambaan;

import android.content.Intent;
import android.os.Bundle;

import androidx.fragment.app.Fragment;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.FrameLayout;
import android.widget.ImageView;

/**
 * A simple {@link Fragment} subclass.
 * Use the {@link QuestionnareFragment#newInstance} factory method to
 * create an instance of this fragment.
 */
public class QuestionnareFragment extends Fragment {

    // TODO: Rename parameter arguments, choose names that match
    // the fragment initialization parameters, e.g. ARG_ITEM_NUMBER
    private static final String ARG_PARAM1 = "param1";
    private static final String ARG_PARAM2 = "param2";

    // TODO: Rename and change types of parameters
    private String mParam1;
    private String mParam2;

    public QuestionnareFragment() {
        // Required empty public constructor
    }

    /**
     * Use this factory method to create a new instance of
     * this fragment using the provided parameters.
     *
     * @param param1 Parameter 1.
     * @param param2 Parameter 2.
     * @return A new instance of fragment QuestionnareFragment.
     */
    // TODO: Rename and change types and number of parameters
    public static QuestionnareFragment newInstance(String param1, String param2) {
        QuestionnareFragment fragment = new QuestionnareFragment();
        Bundle args = new Bundle();
        args.putString(ARG_PARAM1, param1);
        args.putString(ARG_PARAM2, param2);
        fragment.setArguments(args);
        return fragment;
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        if (getArguments() != null) {
            mParam1 = getArguments().getString(ARG_PARAM1);
            mParam2 = getArguments().getString(ARG_PARAM2);
        }
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        // Inflate the layout for this fragment
        View rootView = inflater.inflate(R.layout.activity_questionnare, container, false);
        ImageView a = rootView.findViewById(R.id.imageView1);
        a.setOnClickListener(this::onClick);
        ImageView b = rootView.findViewById(R.id.imageView2);
        b.setOnClickListener(this::onClick);
        ImageView c = rootView.findViewById(R.id.imageView3);
        c.setOnClickListener(this::onClick);
        ImageView d = rootView.findViewById(R.id.imageView4);
        d.setOnClickListener(this::onClick);
        ImageView e = rootView.findViewById(R.id.imageView5);
        e.setOnClickListener(this::onClick);
        ImageView f = rootView.findViewById(R.id.imageView6);
        f.setOnClickListener(this::onClick);
        ImageView g = rootView.findViewById(R.id.imageView7);
        g.setOnClickListener(this::onClick);
        ImageView h = rootView.findViewById(R.id.imageView8);
        h.setOnClickListener(this::onClick);
        ImageView i = rootView.findViewById(R.id.imageView9);
        i.setOnClickListener(this::onClick);
        ImageView j = rootView.findViewById(R.id.imageView10);
        j.setOnClickListener(this::onClick);
        ImageView k = rootView.findViewById(R.id.imageView11);
        k.setOnClickListener(this::onClick);
        ImageView l = rootView.findViewById(R.id.imageView12);
        l.setOnClickListener(this::onClick);
        ImageView m = rootView.findViewById(R.id.imageView13);
        m.setOnClickListener(this::onClick);
        ImageView n = rootView.findViewById(R.id.imageView14);
        n.setOnClickListener(this::onClick);
        ImageView o = rootView.findViewById(R.id.imageView15);
        o.setOnClickListener(this::onClick);
        ImageView p = rootView.findViewById(R.id.imageView16);
        p.setOnClickListener(this::onClick);
        ImageView q = rootView.findViewById(R.id.imageView17);
        q.setOnClickListener(this::onClick);
        ImageView r = rootView.findViewById(R.id.imageView18);
        r.setOnClickListener(this::onClick);
        ImageView s = rootView.findViewById(R.id.imageView19);
        s.setOnClickListener(this::onClick);
        ImageView t = rootView.findViewById(R.id.imageView20);
        t.setOnClickListener(this::onClick);
        ImageView u = rootView.findViewById(R.id.imageView21);
        u.setOnClickListener(this::onClick);
        ImageView v = rootView.findViewById(R.id.imageView22);
        v.setOnClickListener(this::onClick);
        ImageView w = rootView.findViewById(R.id.imageView23);
        w.setOnClickListener(this::onClick);
        ImageView x = rootView.findViewById(R.id.imageView24);
        x.setOnClickListener(this::onClick);
        ImageView y = rootView.findViewById(R.id.imageView25);
        y.setOnClickListener(this::onClick);
        ImageView z = rootView.findViewById(R.id.imageView26);
        z.setOnClickListener(this::onClick);
        ImageView aa = rootView.findViewById(R.id.imageView27);
        aa.setOnClickListener(this::onClick);
        ImageView ab = rootView.findViewById(R.id.imageView28);
        ab.setOnClickListener(this::onClick);
        ImageView ac = rootView.findViewById(R.id.imageView29);
        ac.setOnClickListener(this::onClick);
        ImageView ad = rootView.findViewById(R.id.imageView30);
        ad.setOnClickListener(this::onClick);
        ImageView ae = rootView.findViewById(R.id.imageView31);
        ae.setOnClickListener(this::onClick);
        ImageView af = rootView.findViewById(R.id.imageView32);
        af.setOnClickListener(this::onClick);
        ImageView ag = rootView.findViewById(R.id.imageView33);
        ag.setOnClickListener(this::onClick);
        ImageView ah = rootView.findViewById(R.id.imageView34);
        ah.setOnClickListener(this::onClick);
        ImageView ai = rootView.findViewById(R.id.imageView35);
        ai.setOnClickListener(this::onClick);
        ImageView aj = rootView.findViewById(R.id.imageView36);
        aj.setOnClickListener(this::onClick);
        ImageView ak = rootView.findViewById(R.id.imageView37);
        ak.setOnClickListener(this::onClick);
        ImageView al = rootView.findViewById(R.id.imageView38);
        al.setOnClickListener(this::onClick);
        ImageView am = rootView.findViewById(R.id.imageView39);
        am.setOnClickListener(this::onClick);
        ImageView an = rootView.findViewById(R.id.imageView40);
        an.setOnClickListener(this::onClick);
        ImageView ao = rootView.findViewById(R.id.imageView41);
        ao.setOnClickListener(this::onClick);
        ImageView ap = rootView.findViewById(R.id.imageView42);
        ap.setOnClickListener(this::onClick);
        ImageView aq = rootView.findViewById(R.id.imageView43);
        aq.setOnClickListener(this::onClick);
        ImageView ar = rootView.findViewById(R.id.imageView44);
        ar.setOnClickListener(this::onClick);
        ImageView as = rootView.findViewById(R.id.imageView45);
        as.setOnClickListener(this::onClick);
        ImageView at = rootView.findViewById(R.id.imageView46);
        at.setOnClickListener(this::onClick);
        ImageView au = rootView.findViewById(R.id.imageView47);
        au.setOnClickListener(this::onClick);
        ImageView av = rootView.findViewById(R.id.imageView48);
        av.setOnClickListener(this::onClick);
        ImageView aw = rootView.findViewById(R.id.imageView49);
        aw.setOnClickListener(this::onClick);
        ImageView ax = rootView.findViewById(R.id.imageView50);
        ax.setOnClickListener(this::onClick);
        ImageView ay = rootView.findViewById(R.id.imageView51);
        ay.setOnClickListener(this::onClick);
        ImageView az = rootView.findViewById(R.id.imageView52);
        az.setOnClickListener(this::onClick);
        ImageView aaa = rootView.findViewById(R.id.imageView53);
        aaa.setOnClickListener(this::onClick);
        ImageView aab = rootView.findViewById(R.id.imageView54);
        aab.setOnClickListener(this::onClick);
        ImageView aac = rootView.findViewById(R.id.imageView55);
        aac.setOnClickListener(this::onClick);
        ImageView aad = rootView.findViewById(R.id.imageView56);
        aad.setOnClickListener(this::onClick);
        ImageView aae = rootView.findViewById(R.id.imageView57);
        aae.setOnClickListener(this::onClick);
        ImageView aaf = rootView.findViewById(R.id.imageView58);
        aaf.setOnClickListener(this::onClick);
        ImageView aag = rootView.findViewById(R.id.imageView59);
        aag.setOnClickListener(this::onClick);
        ImageView aah = rootView.findViewById(R.id.imageView60);
        aah.setOnClickListener(this::onClick);
        ImageView aai = rootView.findViewById(R.id.imageView61);
        aai.setOnClickListener(this::onClick);
        ImageView aaj = rootView.findViewById(R.id.imageView62);
        aaj.setOnClickListener(this::onClick);
        ImageView aak = rootView.findViewById(R.id.imageView63);
        aak.setOnClickListener(this::onClick);
        ImageView aal = rootView.findViewById(R.id.imageView64);
        aal.setOnClickListener(this::onClick);
        ImageView aam = rootView.findViewById(R.id.imageView65);
        aam.setOnClickListener(this::onClick);
        ImageView aan = rootView.findViewById(R.id.imageView66);
        aan.setOnClickListener(this::onClick);
        ImageView aao = rootView.findViewById(R.id.imageView67);
        aao.setOnClickListener(this::onClick);
        ImageView aap = rootView.findViewById(R.id.imageView68);
        aap.setOnClickListener(this::onClick);
        ImageView aaq = rootView.findViewById(R.id.imageView69);
        aaq.setOnClickListener(this::onClick);
        ImageView aar = rootView.findViewById(R.id.imageView70);
        aar.setOnClickListener(this::onClick);
        ImageView aas = rootView.findViewById(R.id.imageView71);
        aas.setOnClickListener(this::onClick);
        ImageView aat = rootView.findViewById(R.id.imageView72);
        aat.setOnClickListener(this::onClick);
        ImageView aau = rootView.findViewById(R.id.imageView73);
        aau.setOnClickListener(this::onClick);
        ImageView aav = rootView.findViewById(R.id.imageView74);
        aav.setOnClickListener(this::onClick);
        ImageView aaw = rootView.findViewById(R.id.imageView75);
        aaw.setOnClickListener(this::onClick);
        ImageView aax = rootView.findViewById(R.id.imageView76);
        aax.setOnClickListener(this::onClick);
        ImageView aay = rootView.findViewById(R.id.imageView77);
        aay.setOnClickListener(this::onClick);
        ImageView aaz = rootView.findViewById(R.id.imageView78);
        aaz.setOnClickListener(this::onClick);
        ImageView aaaa = rootView.findViewById(R.id.imageView79);
        aaaa.setOnClickListener(this::onClick);
        ImageView aaab = rootView.findViewById(R.id.imageView80);
        aaab.setOnClickListener(this::onClick);
        ImageView aaac = rootView.findViewById(R.id.imageView81);
        aaac.setOnClickListener(this::onClick);
        ImageView aaad = rootView.findViewById(R.id.imageView82);
        aaad.setOnClickListener(this::onClick);
        ImageView aaae = rootView.findViewById(R.id.imageView83);
        aaae.setOnClickListener(this::onClick);
        ImageView aaaf = rootView.findViewById(R.id.imageView84);
        aaaf.setOnClickListener(this::onClick);
        ImageView aaag = rootView.findViewById(R.id.imageView85);
        aaag.setOnClickListener(this::onClick);
        ImageView aaah = rootView.findViewById(R.id.imageView86);
        aaah.setOnClickListener(this::onClick);
        ImageView aaai = rootView.findViewById(R.id.imageView87);
        aaai.setOnClickListener(this::onClick);
        ImageView aaaj = rootView.findViewById(R.id.imageView88);
        aaaj.setOnClickListener(this::onClick);
        ImageView aaak = rootView.findViewById(R.id.imageView89);
        aaak.setOnClickListener(this::onClick);
        ImageView aaal = rootView.findViewById(R.id.imageView90);
        aaal.setOnClickListener(this::onClick);
        ImageView aaam = rootView.findViewById(R.id.imageView91);
        aaam.setOnClickListener(this::onClick);
        ImageView aaan = rootView.findViewById(R.id.imageView92);
        aaan.setOnClickListener(this::onClick);
        ImageView aaao = rootView.findViewById(R.id.imageView93);
        aaao.setOnClickListener(this::onClick);
        ImageView aaap = rootView.findViewById(R.id.imageView94);
        aaap.setOnClickListener(this::onClick);
        ImageView aaaq = rootView.findViewById(R.id.imageView95);
        aaaq.setOnClickListener(this::onClick);
        ImageView aaar = rootView.findViewById(R.id.imageView96);
        aaar.setOnClickListener(this::onClick);
        ImageView aaas = rootView.findViewById(R.id.imageView97);
        aaas.setOnClickListener(this::onClick);
        ImageView aaat = rootView.findViewById(R.id.imageView98);
        aaat.setOnClickListener(this::onClick);
        ImageView aaau = rootView.findViewById(R.id.imageView99);
        aaau.setOnClickListener(this::onClick);
        ImageView aaav = rootView.findViewById(R.id.imageView100);
        aaav.setOnClickListener(this::onClick);
        ImageView aaaw = rootView.findViewById(R.id.imageView101);
        aaaw.setOnClickListener(this::onClick);
        ImageView aaax = rootView.findViewById(R.id.imageView102);
        aaax.setOnClickListener(this::onClick);
        ImageView aaay = rootView.findViewById(R.id.imageView103);
        aaay.setOnClickListener(this::onClick);
        ImageView aaaz = rootView.findViewById(R.id.imageView104);
        aaaz.setOnClickListener(this::onClick);
        ImageView aaaaa = rootView.findViewById(R.id.imageView105);
        aaaaa.setOnClickListener(this::onClick);
        ImageView aaaab = rootView.findViewById(R.id.imageView106);
        aaaab.setOnClickListener(this::onClick);
        ImageView aaaac = rootView.findViewById(R.id.imageView107);
        aaaac.setOnClickListener(this::onClick);
        ImageView aaaad = rootView.findViewById(R.id.imageView108);
        aaaad.setOnClickListener(this::onClick);
        ImageView aaaae = rootView.findViewById(R.id.imageView109);
        aaaae.setOnClickListener(this::onClick);
        ImageView aaaaf = rootView.findViewById(R.id.imageView110);
        aaaaf.setOnClickListener(this::onClick);
        ImageView aaaag = rootView.findViewById(R.id.imageView111);
        aaaag.setOnClickListener(this::onClick);
        ImageView aaaah = rootView.findViewById(R.id.imageView112);
        aaaah.setOnClickListener(this::onClick);
        ImageView aaaai = rootView.findViewById(R.id.imageView113);
        aaaai.setOnClickListener(this::onClick);
        ImageView aaaaj = rootView.findViewById(R.id.imageView114);
        aaaaj.setOnClickListener(this::onClick);
        ImageView aaaak = rootView.findViewById(R.id.imageView115);
        aaaak.setOnClickListener(this::onClick);
        ImageView aaaal = rootView.findViewById(R.id.imageView116);
        aaaal.setOnClickListener(this::onClick);
        ImageView aaaam = rootView.findViewById(R.id.imageView117);
        aaaam.setOnClickListener(this::onClick);
        ImageView aaaan = rootView.findViewById(R.id.imageView118);
        aaaan.setOnClickListener(this::onClick);
        ImageView aaaao = rootView.findViewById(R.id.imageView119);
        aaaao.setOnClickListener(this::onClick);
        ImageView aaaap = rootView.findViewById(R.id.imageView120);
        aaaap.setOnClickListener(this::onClick);
        ImageView aaaaq = rootView.findViewById(R.id.imageView121);
        aaaaq.setOnClickListener(this::onClick);
        ImageView aaaar = rootView.findViewById(R.id.imageView122);
        aaaar.setOnClickListener(this::onClick);
        ImageView aaaas = rootView.findViewById(R.id.imageView123);
        aaaas.setOnClickListener(this::onClick);
        ImageView aaaat = rootView.findViewById(R.id.imageView124);
        aaaat.setOnClickListener(this::onClick);
        ImageView aaaau = rootView.findViewById(R.id.imageView125);
        aaaau.setOnClickListener(this::onClick);
        ImageView aaaav = rootView.findViewById(R.id.imageView126);
        aaaav.setOnClickListener(this::onClick);
        ImageView aaaaw = rootView.findViewById(R.id.imageView127);
        aaaaw.setOnClickListener(this::onClick);
        ImageView aaaax = rootView.findViewById(R.id.imageView128);
        aaaax.setOnClickListener(this::onClick);
        ImageView aaaay = rootView.findViewById(R.id.imageView129);
        aaaay.setOnClickListener(this::onClick);
        ImageView aaaaz = rootView.findViewById(R.id.imageView130);
        aaaaz.setOnClickListener(this::onClick);
        ImageView aaaaaa = rootView.findViewById(R.id.imageView131);
        aaaaaa.setOnClickListener(this::onClick);
        ImageView aaaaab = rootView.findViewById(R.id.imageView132);
        aaaaab.setOnClickListener(this::onClick);
        ImageView aaaaac = rootView.findViewById(R.id.imageView133);
        aaaaac.setOnClickListener(this::onClick);
        ImageView aaaaad = rootView.findViewById(R.id.imageView134);
        aaaaad.setOnClickListener(this::onClick);
        ImageView aaaaae = rootView.findViewById(R.id.imageView135);
        aaaaae.setOnClickListener(this::onClick);
        ImageView aaaaaf = rootView.findViewById(R.id.imageView136);
        aaaaaf.setOnClickListener(this::onClick);
        ImageView aaaaag = rootView.findViewById(R.id.imageView137);
        aaaaag.setOnClickListener(this::onClick);
        ImageView aaaaah = rootView.findViewById(R.id.imageView138);
        aaaaah.setOnClickListener(this::onClick);
        ImageView aaaaai = rootView.findViewById(R.id.imageView139);
        aaaaai.setOnClickListener(this::onClick);
        ImageView aaaaaj = rootView.findViewById(R.id.imageView140);
        aaaaaj.setOnClickListener(this::onClick);
        ImageView aaaaak = rootView.findViewById(R.id.imageView141);
        aaaaak.setOnClickListener(this::onClick);
        ImageView aaaaal = rootView.findViewById(R.id.imageView142);
        aaaaal.setOnClickListener(this::onClick);
        ImageView aaaaam = rootView.findViewById(R.id.imageView143);
        aaaaam.setOnClickListener(this::onClick);
        ImageView aaaaan = rootView.findViewById(R.id.imageView144);
        aaaaan.setOnClickListener(this::onClick);
        ImageView aaaaao = rootView.findViewById(R.id.imageView145);
        aaaaao.setOnClickListener(this::onClick);
        ImageView aaaaap = rootView.findViewById(R.id.imageView146);
        aaaaap.setOnClickListener(this::onClick);
        ImageView aaaaaq = rootView.findViewById(R.id.imageView147);
        aaaaaq.setOnClickListener(this::onClick);
        ImageView aaaaar = rootView.findViewById(R.id.imageView148);
        aaaaar.setOnClickListener(this::onClick);
        ImageView aaaaas = rootView.findViewById(R.id.imageView149);
        aaaaas.setOnClickListener(this::onClick);
        ImageView aaaaat = rootView.findViewById(R.id.imageView150);
        aaaaat.setOnClickListener(this::onClick);
        ImageView aaaaau = rootView.findViewById(R.id.imageView151);
        aaaaau.setOnClickListener(this::onClick);
        ImageView aaaaav = rootView.findViewById(R.id.imageView152);
        aaaaav.setOnClickListener(this::onClick);
        ImageView aaaaaw = rootView.findViewById(R.id.imageView153);
        aaaaaw.setOnClickListener(this::onClick);
        ImageView aaaaax = rootView.findViewById(R.id.imageView154);
        aaaaax.setOnClickListener(this::onClick);
        ImageView aaaaay = rootView.findViewById(R.id.imageView155);
        aaaaay.setOnClickListener(this::onClick);
        ImageView aaaaaz = rootView.findViewById(R.id.imageView156);
        aaaaaz.setOnClickListener(this::onClick);
        ImageView aaaaaaa = rootView.findViewById(R.id.imageView157);
        aaaaaaa.setOnClickListener(this::onClick);
        ImageView aaaaaab = rootView.findViewById(R.id.imageView158);
        aaaaaab.setOnClickListener(this::onClick);
        ImageView aaaaaac = rootView.findViewById(R.id.imageView159);
        aaaaaac.setOnClickListener(this::onClick);
        ImageView aaaaaad = rootView.findViewById(R.id.imageView160);
        aaaaaad.setOnClickListener(this::onClick);
        ImageView aaaaaae = rootView.findViewById(R.id.imageView161);
        aaaaaae.setOnClickListener(this::onClick);
        ImageView aaaaaaf = rootView.findViewById(R.id.imageView162);
        aaaaaaf.setOnClickListener(this::onClick);
        ImageView aaaaaag = rootView.findViewById(R.id.imageView163);
        aaaaaag.setOnClickListener(this::onClick);
        ImageView aaaaaah = rootView.findViewById(R.id.imageView164);
        aaaaaah.setOnClickListener(this::onClick);
        ImageView aaaaaai = rootView.findViewById(R.id.imageView165);
        aaaaaai.setOnClickListener(this::onClick);
        ImageView aaaaaaj = rootView.findViewById(R.id.imageView166);
        aaaaaaj.setOnClickListener(this::onClick);
        ImageView aaaaaak = rootView.findViewById(R.id.imageView167);
        aaaaaak.setOnClickListener(this::onClick);
        ImageView aaaaaal = rootView.findViewById(R.id.imageView168);
        aaaaaal.setOnClickListener(this::onClick);
        ImageView aaaaaam = rootView.findViewById(R.id.imageView169);
        aaaaaam.setOnClickListener(this::onClick);
        ImageView aaaaaan = rootView.findViewById(R.id.imageView170);
        aaaaaan.setOnClickListener(this::onClick);
        ImageView aaaaaao = rootView.findViewById(R.id.imageView171);
        aaaaaao.setOnClickListener(this::onClick);
        ImageView aaaaaap = rootView.findViewById(R.id.imageView172);
        aaaaaap.setOnClickListener(this::onClick);
        ImageView aaaaaaq = rootView.findViewById(R.id.imageView173);
        aaaaaaq.setOnClickListener(this::onClick);
        ImageView aaaaaar = rootView.findViewById(R.id.imageView174);
        aaaaaar.setOnClickListener(this::onClick);
        ImageView aaaaaas = rootView.findViewById(R.id.imageView175);
        aaaaaas.setOnClickListener(this::onClick);
        ImageView aaaaaat = rootView.findViewById(R.id.imageView176);
        aaaaaat.setOnClickListener(this::onClick);
        ImageView aaaaaau = rootView.findViewById(R.id.imageView177);
        aaaaaau.setOnClickListener(this::onClick);
        ImageView aaaaaav = rootView.findViewById(R.id.imageView178);
        aaaaaav.setOnClickListener(this::onClick);
        ImageView aaaaaaw = rootView.findViewById(R.id.imageView179);
        aaaaaaw.setOnClickListener(this::onClick);
        ImageView aaaaaax = rootView.findViewById(R.id.imageView180);
        aaaaaax.setOnClickListener(this::onClick);
        ImageView aaaaaay = rootView.findViewById(R.id.imageView181);
        aaaaaay.setOnClickListener(this::onClick);
        ImageView aaaaaaz = rootView.findViewById(R.id.imageView182);
        aaaaaaz.setOnClickListener(this::onClick);
        ImageView aaaaaaaa = rootView.findViewById(R.id.imageView183);
        aaaaaaaa.setOnClickListener(this::onClick);
        ImageView aaaaaaab = rootView.findViewById(R.id.imageView184);
        aaaaaaab.setOnClickListener(this::onClick);
        ImageView aaaaaaac = rootView.findViewById(R.id.imageView185);
        aaaaaaac.setOnClickListener(this::onClick);
        ImageView aaaaaaad = rootView.findViewById(R.id.imageView186);
        aaaaaaad.setOnClickListener(this::onClick);
        ImageView aaaaaaae = rootView.findViewById(R.id.imageView187);
        aaaaaaae.setOnClickListener(this::onClick);
        ImageView aaaaaaaf = rootView.findViewById(R.id.imageView188);
        aaaaaaaf.setOnClickListener(this::onClick);
        ImageView aaaaaaag = rootView.findViewById(R.id.imageView189);
        aaaaaaag.setOnClickListener(this::onClick);
        ImageView aaaaaaah = rootView.findViewById(R.id.imageView190);
        aaaaaaah.setOnClickListener(this::onClick);
        ImageView aaaaaaai = rootView.findViewById(R.id.imageView191);
        aaaaaaai.setOnClickListener(this::onClick);
        ImageView aaaaaaaj = rootView.findViewById(R.id.imageView192);
        aaaaaaaj.setOnClickListener(this::onClick);
        ImageView aaaaaaak = rootView.findViewById(R.id.imageView193);
        aaaaaaak.setOnClickListener(this::onClick);
        ImageView aaaaaaal = rootView.findViewById(R.id.imageView194);
        aaaaaaal.setOnClickListener(this::onClick);
        ImageView aaaaaaam = rootView.findViewById(R.id.imageView195);
        aaaaaaam.setOnClickListener(this::onClick);
        ImageView aaaaaaan = rootView.findViewById(R.id.imageView196);
        aaaaaaan.setOnClickListener(this::onClick);
        ImageView aaaaaaao = rootView.findViewById(R.id.imageView197);
        aaaaaaao.setOnClickListener(this::onClick);
        ImageView aaaaaaap = rootView.findViewById(R.id.imageView198);
        aaaaaaap.setOnClickListener(this::onClick);
        ImageView aaaaaaaq = rootView.findViewById(R.id.imageView199);
        aaaaaaaq.setOnClickListener(this::onClick);
        ImageView aaaaaaar = rootView.findViewById(R.id.imageView200);
        aaaaaaar.setOnClickListener(this::onClick);
        ImageView aaaaaaas = rootView.findViewById(R.id.imageView201);
        aaaaaaas.setOnClickListener(this::onClick);
        ImageView aaaaaaat = rootView.findViewById(R.id.imageView202);
        aaaaaaat.setOnClickListener(this::onClick);
        ImageView aaaaaaau = rootView.findViewById(R.id.imageView203);
        aaaaaaau.setOnClickListener(this::onClick);
        ImageView aaaaaaav = rootView.findViewById(R.id.imageView204);
        aaaaaaav.setOnClickListener(this::onClick);
        ImageView aaaaaaaw = rootView.findViewById(R.id.imageView205);
        aaaaaaaw.setOnClickListener(this::onClick);
        ImageView aaaaaaax = rootView.findViewById(R.id.imageView206);
        aaaaaaax.setOnClickListener(this::onClick);
        ImageView aaaaaaay = rootView.findViewById(R.id.imageView207);
        aaaaaaay.setOnClickListener(this::onClick);
        ImageView aaaaaaaz = rootView.findViewById(R.id.imageView208);
        aaaaaaaz.setOnClickListener(this::onClick);
        ImageView aaaaaaaaa = rootView.findViewById(R.id.imageView209);
        aaaaaaaaa.setOnClickListener(this::onClick);
        ImageView aaaaaaaab = rootView.findViewById(R.id.imageView210);
        aaaaaaaab.setOnClickListener(this::onClick);
        ImageView aaaaaaaac = rootView.findViewById(R.id.imageView211);
        aaaaaaaac.setOnClickListener(this::onClick);
        ImageView aaaaaaaad = rootView.findViewById(R.id.imageView212);
        aaaaaaaad.setOnClickListener(this::onClick);
        ImageView aaaaaaaae = rootView.findViewById(R.id.imageView213);
        aaaaaaaae.setOnClickListener(this::onClick);
        ImageView aaaaaaaaf = rootView.findViewById(R.id.imageView214);
        aaaaaaaaf.setOnClickListener(this::onClick);
        ImageView aaaaaaaag = rootView.findViewById(R.id.imageView215);
        aaaaaaaag.setOnClickListener(this::onClick);
        ImageView aaaaaaaah = rootView.findViewById(R.id.imageView216);
        aaaaaaaah.setOnClickListener(this::onClick);
        ImageView aaaaaaaai = rootView.findViewById(R.id.imageView217);
        aaaaaaaai.setOnClickListener(this::onClick);
        ImageView aaaaaaaaj = rootView.findViewById(R.id.imageView218);
        aaaaaaaaj.setOnClickListener(this::onClick);
        ImageView aaaaaaaak = rootView.findViewById(R.id.imageView219);
        aaaaaaaak.setOnClickListener(this::onClick);
        ImageView aaaaaaaal = rootView.findViewById(R.id.imageView220);
        aaaaaaaal.setOnClickListener(this::onClick);
        ImageView aaaaaaaam = rootView.findViewById(R.id.imageView221);
        aaaaaaaam.setOnClickListener(this::onClick);
        ImageView aaaaaaaan = rootView.findViewById(R.id.imageView222);
        aaaaaaaan.setOnClickListener(this::onClick);
        ImageView aaaaaaaao = rootView.findViewById(R.id.imageView223);
        aaaaaaaao.setOnClickListener(this::onClick);
        ImageView aaaaaaaap = rootView.findViewById(R.id.imageView224);
        aaaaaaaap.setOnClickListener(this::onClick);
        ImageView aaaaaaaaq = rootView.findViewById(R.id.imageView225);
        aaaaaaaaq.setOnClickListener(this::onClick);
        return rootView;
    }

    public void onClick(View view){
        int id = view.getId();
        Intent intent = new Intent(getActivity(),output.class);
        intent.putExtra("vid",id);
        startActivity(intent);
    }

}